$ opam depext -iy -j 2 dockerfile.1.2.1
# Detecting depexts using vars: arch=x86_64, os=linux, os-distribution=debian, os-family=debian
[ERROR] No solution for dockerfile.1.2.1: The following dependencies couldn't be met:
          - dockerfile -> camlp4 -> ocaml-variants (= 4.02.0+modular-implicits & = 4.02.1+modular-implicits-ber)
              no matching version
          - dockerfile -> camlp4 -> ocaml < 4.08
              base of this switch (use `--unlock-base' to force)


Command failed: opam list --readonly --external  --resolve=dockerfile.1.2.1 returned 20
20 1533438137 1533438139