$ opam depext -iy -j 2 dockerfile.1.3.0
# Detecting depexts using vars: arch=x86_64, os=linux, os-distribution=debian, os-family=debian
[ERROR] No solution for dockerfile.1.3.0: The following dependencies couldn't be met:
          - dockerfile -> ocaml < 4.06.0
              base of this switch (use `--unlock-base' to force)


Command failed: opam list --readonly --external  --resolve=dockerfile.1.3.0 returned 20
20 1535575829 1535575831