$ opam depext -iy -j 2 dockerfile.1.7.0
# Detecting depexts using vars: arch=x86_64, os=linux, os-distribution=ubuntu, os-family=debian
[ERROR] No solution for dockerfile.1.7.0: The following dependencies couldn't be met:
          - dockerfile -> ocaml < 4.06.0
              base of this switch (use `--unlock-base' to force)


Command failed: opam list --readonly --external  --resolve=dockerfile.1.7.0 returned 20
20 1534289880 1534289883