$ opam depext -iy -j 2 dockerfile.2.2.2
# Detecting depexts using vars: arch=x86_64, os=linux, os-distribution=debian, os-family=debian
[ERROR] No solution for dockerfile.2.2.2: The following dependencies couldn't be met:
          - dockerfile -> ppx_deriving -> ppx_tools >= 4.02.3 -> ocaml < 4.08
              base of this switch (use `--unlock-base' to force)
          - dockerfile -> ppx_deriving -> ocaml < 4.06.0
              base of this switch (use `--unlock-base' to force)


Command failed: opam list --readonly --external  --resolve=dockerfile.2.2.2 returned 20
20 1532896443 1532896446