$ opam depext -iy -j 2 dockerfile.1.2.1
# Detecting depexts using vars: arch=x86_64, os=linux, os-distribution=opensuse, os-family=suse
[ERROR] No solution for dockerfile.1.2.1: The following dependencies couldn't be met:
          - dockerfile -> sexplib < 113.24.00 -> ocaml < 4.03.0
              base of this switch (use `--unlock-base' to force)


Command failed: opam list --readonly --external  --resolve=dockerfile.1.2.1 returned 20
20 1532667223 1532667226